[package]
name = "runtime_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
axum = "0.7"
futures = "0.3"
hyper = { version = "0.14", features = ["full"] }
md5 = "0.7.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
thiserror = "1.0"
toml = "0.8"
uuid = { version = "1.0", features = ["v4"] }
wasmtime = { version = "27.0.0", features = ["component-model"] }
clap = { version = "4.4", features = ["derive"] }
axum-macros = "0.4.2"
tide = "0.16.0"
async-trait = "0.1"
