[package]
name = "runtime_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
axum = "0.7"
futures = "0.3"
md5 = "0.7.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
toml = "0.8"
wasmtime = { version = "27.0.0", features = ["component-model"] }
clap = { version = "4.4", features = ["derive"] }
