name = "actor4"
version = "0.1.0"
description = "Sample actor for testing manifest loading"

component_path = "/Users/colinrozzi/work/experimenting/3/actors/actor4/target/wasm32-unknown-unknown/release/actor4.wasm"

[interface]
implements = "ntwk:simple-actor/actor"
requires = []

[capabilities.host]

[capabilities.actors]

[config]
