name = ""
version = "0.1.0"
description = "Sample actor for testing http host system capabilities"

component_path = "/Users/colinrozzi/work/experimenting/3/actors/first-http-actor/target/wasm32-unknown-unknown/release/first_http_actor.wasm"

[interface]
implements = "ntwk:simple-http-actor/http-actor"
requires = []

[capabilities.host]
http = { addr = "127.0.0.1:8080" }

[capabilities.actors]

[config]

